### ISSUE TITLE
tuple index out of range

### ISSUE THREAD

**Issue by sicenul** [djentleman/imgrender#2]
* I'd like to render an image to terminal console. The image is a black and white qrcode
* Executing this snippet inside python 3.7 script:
```
from imgrender import render
filename = 'qrcode.png'
render(filename, scale=(256, 256))
```
* Resulting in this following error. What is the possibility of this error? 
```
Traceback (most recent call last):
  File "main.py", line 38, in <module>
    render(filename, scale=(256, 256))
  File "/home/yooza/python/wa-notif/env/lib/python3.7/site-packages/imgrender/main.py", line 37, in render
    image = get_image(path)
  File "/home/yooza/python/wa-notif/env/lib/python3.7/site-packages/imgrender/main.py", line 31, in get_image
    if img.shape[2] > 3:
IndexError: tuple index out of range
```

**Comment by djentleman** [comment]
I've managed to reproduce this and i will fix it - I'm guessing its something to do with the way monochrome data is stored

**Comment by djentleman** [comment]
https://github.com/djentleman/imgrender/pull/3

this should fix it

**Comment by djentleman** [comment]
I released a new version with the fix - install
```
pip install imgrender==0.0.3
```
and try again

**Comment by sicenul** [comment]
Thanks, the index error is fixed. But it looks like cannot be used for qrcode :smiley: 
I cannot scan the qrcode because it has grey gradation, or maybe there's an option to show black and white only?
And i don't know why my qrcode showed blank. This is the sample of [my image](https://i.ibb.co/bz9vdRk/qrcode.png).

**Comment by djentleman** [comment]
Thanks for sending the file over - I will have a look when I have time later in the week.
To remove the gray areas you can try making the height and width divisible by the original image size - the gray is a result of white and black pixels overlapping, and the imgrender code calculates the average colour. For a 256×256 image try a height/width of 128x128 or 64x64
