### ISSUE TITLE
Update to recent numpy version

### ISSUE THREAD

**Issue by B0-B** [djentleman/imgrender#7]
When I am installing via  **pip install imgrender==0.0.3** it  first uninstalls (without asking) my current numpy-package which is crucial for plenty of other software .
Subsequently it falls back to numpy 1.17.2:

`pip install imgrender==0.0.3
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: imgrender==0.0.3 in /home/b1/.local/lib/python3.6/site-packages (0.0.3)
Collecting numpy==1.17.2
  Using cached numpy-1.17.2-cp36-cp36m-manylinux1_x86_64.whl (20.4 MB)
Requirement already satisfied: ansicolors==1.1.8 in /home/b1/.local/lib/python3.6/site-packages (from imgrender==0.0.3) (1.1.8)
Requirement already satisfied: Pillow==6.1.0 in /home/b1/.local/lib/python3.6/site-packages (from imgrender==0.0.3) (6.1.0)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.5
    Uninstalling numpy-1.19.5:
      Successfully uninstalled numpy-1.19.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.4.1 requires numpy~=1.19.2, but you have numpy 1.17.2 which is incompatible.
Successfully installed numpy-1.17.2`

I have never seen a strong version dependency on any scientific kit, you should rethink this and always use the recent stable release. However even after getting numpy 1.17 I am receiving 

`timg LABEL.png
Traceback (most recent call last):
  File "/home/b1/.local/bin/timg", line 8, in <module>
    sys.exit(main())
  File "/home/b1/.local/lib/python3.6/site-packages/timg/__main__.py", line 62, in main
    renderer.render(method)
  File "/home/b1/.local/lib/python3.6/site-packages/timg/renderer.py", line 32, in render
    print(method.to_string())
  File "/home/b1/.local/lib/python3.6/site-packages/timg/methods/ansi_methods.py", line 31, in to_string
    return ANSIMethod(self.image).to_24_bit_hblock()
  File "/home/b1/.local/lib/python3.6/site-packages/timg/methods/ansi.py", line 83, in to_24_bit_hblock
    return self.to_block(24, hblock=True)
  File "/home/b1/.local/lib/python3.6/site-packages/timg/methods/ansi.py", line 56, in to_block
    fg_color = pix[x, y+1][:3]
TypeError: 'int' object is not subscriptable`

``
it only works for jpegs.

**Comment by ghost** [comment]
apologies for the year long delay
this should be fixed now with version 0.0.4
https://pypi.org/project/imgrender/
